# Generated by Django 6.0.4 on 2026-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_online_user_last_seen_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='defaults/default_profile.jpg', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
