# Generated by Django 6.0.4 on 2026-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
